# Generated by Django 3.0.5 on 2020-04-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FillingTypeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('option1', models.CharField(default='', max_length=100)),
                ('option2', models.CharField(default='', max_length=100)),
                ('option3', models.CharField(default='', max_length=100)),
                ('option4', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageTypeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('image', models.ImageField(default='', upload_to='practice_question/images')),
                ('option1', models.CharField(default='', max_length=100)),
                ('option2', models.CharField(default='', max_length=100)),
                ('option3', models.CharField(default='', max_length=100)),
                ('option4', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassageTypeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('option1', models.CharField(default='', max_length=100)),
                ('option2', models.CharField(default='', max_length=100)),
                ('option3', models.CharField(default='', max_length=100)),
                ('option4', models.CharField(default='', max_length=100)),
                ('answer', models.CharField(default='', max_length=100)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
