# Generated by Django 3.0.5 on 2020-04-22 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200422_0749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audio',
            options={'ordering': ['book']},
        ),
    ]
