# Generated by Django 3.0.5 on 2020-04-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200422_0751'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
